image: silex/emacs:master-dev

before_script:
  - apt-get update && apt-get install -y rsync

stages:
  - build

build:
  stage: build
  script:
    - ./mirror-elpa .ci/github.config
  only:
    - master
